Friendships v2
AdfPizarro/ror-social-scaffold pull request #3
Opened 2020-11-15 01:57 UTC by AdfPizarro

As far as I understand the 2 row friendships and the valitations are already in the previous milestone please tell me if there is something else i have to do

2020-11-15 03:17 UTC, krys2fa requested changes
## Well done @AdfPizarro 👏 
Your project is coming along nicely.👍 

Just a few more adjustments to complete the project. They can be seen below:
### Status: Changes Required ♻️ 

- [ ] [REQUIRED] In this milestone, it is expected that when friendship is confirmed, an additional row with a reversed user-friend pair is created. See below for an example.
``` 
#Friendship model
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

2020-11-15 03:17 UTC, krys2fa commented on .rubocop.yml
> -Lint/RaiseException:
- [ ] Please do not edit the linter files. They represent guidelines for all students. 
Hint: Research on how to disable cops in a file.

2020-11-19 23:18 UTC, AdfPizarro commented on .rubocop.yml
> -Lint/RaiseException:
Done, thanks

2020-11-20 00:44 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

Hello @AdfPizarro, Great job! 👏 

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.

- [x] in order to get all posts written by a user on their friends, students can use a simple method in the User model (in order to NOT do it with Enumerable)
```ruby
def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

- [x] Keep your codebase clean by removing unused files (`user.rb.save, user.rb.save1, user.rb.save2`), If you need to review a previous version of your code, use git history or simply add them to .gitignore.

- [x] You seem to be missing **validation** tests for your models, ensuring the name of a user is present, the content of a post is present, and so on.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-20 00:44 UTC, acushlakoncept commented on app/models/user.rb
> +  end
In friendship V2, we will use SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

2020-11-20 00:44 UTC, acushlakoncept commented on app/models/user.rb
> +  end
On the same note that the database was created to store and query data, it is always more efficient than ruby, we will use
```ruby
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```

2020-11-20 00:44 UTC, acushlakoncept commented on app/models/user.rb
> +  end
On the same note that the database was created to store and query data, it is always more efficient than ruby, we will use
```ruby
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```

2020-11-20 00:44 UTC, acushlakoncept commented on app/models/user.rb
> +  end
thanks to the SQL query things are a lot easier when friendship is confirmed, an additional row with reversed user-friend pair is created
```ruby
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

2020-11-20 00:44 UTC, acushlakoncept commented on spec/models/friendship_spec.rb
> +require 'rails_helper.rb'
Using require_relative for files in your directory instead of `require` is a ruby convention.
"Require should be used for external files, like gems, while `require_relative` should be used for referring to files within your directory."

2020-11-20 00:44 UTC, acushlakoncept commented on spec/features/friendship_spec.rb
> +require 'rails_helper.rb'
Using require_relative for files in your directory instead of `require` is a ruby convention.
"Require should be used for external files, like gems, while `require_relative` should be used for referring to files within your directory."

2020-11-20 00:44 UTC, acushlakoncept commented on spec/models/user_spec.rb
> +require 'rails_helper.rb'
Using require_relative for files in your directory instead of `require` is a ruby convention.
"Require should be used for external files, like gems, while `require_relative` should be used for referring to files within your directory."

2020-11-20 00:44 UTC, acushlakoncept commented on README.md
>  ```
You've got a typo error here, kindly update to `rspec --format documentation`
Note you can add `--format documentation` to line 2 of `.rspec` file in your root directory so you will just need to type only `rspec` yet still have the same result.

2020-11-23 21:11 UTC, AdfPizarro commented on app/models/user.rb
> +  end
Thanks, thats a really cool way to do it

2020-11-23 21:55 UTC, AdfPizarro commented on app/models/user.rb
> +  end
U[dated to replace the map

2020-11-23 21:55 UTC, AdfPizarro commented on app/models/user.rb
> +  end
this doesn't work in this context, the views are made in a different way I'll keep the previous method

2020-11-23 22:02 UTC, AdfPizarro commented on README.md
>  ```
Updated, thanks

2020-11-23 23:03 UTC, AdfPizarro commented on spec/models/user_spec.rb
> +require 'rails_helper.rb'
The files are outside the folder so require relative is not the best option if I use require relative I need to give an absolute path as far is found after some reserch

2020-11-24 02:20 UTC, AdfPizarro commented on spec/models/user_spec.rb
> +require 'rails_helper.rb'
Done

2020-11-24 03:29 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED 🛑 

A great job implementing the previously suggested changes 👍 
I can see you have put a to of effort in this project 👏 
Just a few adjustments and ready to go 💪 
Kindly check my comments below 👇  apply the changes and request for a new code review ⏩ 
Good luck 😺 
## Mandatory changes
- Add tests for all your models(comments, likes, post...), validations and helpers in your model's files, let's be sure everything is working properly before deploying into production

2020-11-24 14:51 UTC, rOluochKe approved these changes
Hello Team
### You got it right, well done. The project has been approved. Congratulations :boom: :100:
### Merge and submit for another code review. Good luck.
- Happy coding!

2020-11-24 15:21 UTC, merged